'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map, MapLayerMouseEvent } from 'maplibre-gl';
import { isStale, type Dataset } from '../../../../packages/contracts';
import { DataState } from '../../components/data-state';
import { Evidence } from '../../components/evidence';
import { EARTHQUAKES_MANIFEST, loadDataset, UnavailableError } from '../../lib/datasets';
import { mountEarthquakeDataset } from '../../lib/map-layers';
import type { Resource } from '../../lib/resource';

export function Earthquakes({ map }: { map: Map | null }) {
  const [resource,setResource]=useState<Resource<Dataset>>({status:'loading'}); const [attempt,setAttempt]=useState(0); const [visible,setVisible]=useState(true); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const [minMag,setMinMag]=useState(4); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const mounted=useRef<ReturnType<typeof mountEarthquakeDataset>|null>(null); const dataset='data' in resource?resource.data:null;
  useEffect(()=>{if(!map)return;const controller=new AbortController();let handle:ReturnType<typeof mountEarthquakeDataset>|null=null;let click:((event:MapLayerMouseEvent)=>void)|null=null;void(async()=>{try{const data=await loadDataset(EARTHQUAKES_MANIFEST,controller.signal);if(controller.signal.aborted)return;handle=mountEarthquakeDataset(map,data);mounted.current=handle;handle.setVisible(visible);handle.setFilter(minMag,start,end);click=e=>{const id=e.features?.[0]?.id;if(id!==undefined)choose(String(id),data);};map.on('click',handle.interactiveLayers,click);setResource({status:isStale(data.metadata)?'stale':data.collection.features.length?'ready':'empty',data});}catch(error){if(!controller.signal.aborted)setResource({status:error instanceof UnavailableError?'unavailable':'error',message:error instanceof Error?error.message:'Earthquake catalog unavailable'});}})();return()=>{controller.abort();if(handle&&click)map.off('click',handle.interactiveLayers,click);handle?.dispose();mounted.current=null;}; // eslint-disable-next-line react-hooks/exhaustive-deps
  },[map,attempt]); useEffect(()=>{mounted.current?.setVisible(visible);},[visible]); useEffect(()=>{mounted.current?.setFilter(minMag,start,end);},[minMag,start,end]);
  const matches=useMemo(()=>{if(!dataset)return[];const needle=query.trim().toLowerCase();return dataset.collection.features.filter(f=>(f.properties.magnitude??-Infinity)>=minMag&&(!start||(f.properties.event_time??'')>=`${start}T00:00:00Z`)&&(!end||(f.properties.event_time??'')<=`${end}T23:59:59Z`)&&(!needle||f.properties.search_terms?.some(t=>t.toLowerCase().includes(needle)))).slice().sort((a,b)=>(b.properties.event_time??'').localeCompare(a.properties.event_time??'')).slice(0,200);},[dataset,query,minMag,start,end]); const feature=dataset?.collection.features.find(f=>String(f.id)===selected);
  function choose(id:string,data=dataset){setSelected(id);mounted.current?.setSelected(id||null);const item=data?.collection.features.find(f=>String(f.id)===id);if(item?.geometry.type==='Point'&&map)map.easeTo({center:item.geometry.coordinates as [number,number],zoom:Math.max(map.getZoom(),8),duration:0});}
  return <section className="thematic-controls" aria-label="Earthquakes" data-earthquakes-state={resource.status}><h2>Earthquakes</h2><p>USGS ComCat · regional catalogue, 2000–2026</p>{map?<DataState state={resource} retry={()=>{setResource({status:'loading'});setAttempt(v=>v+1);}}/>:<p className="muted">Earthquake controls require the map.</p>}<label><input type="checkbox" checked={visible} disabled={!dataset} onChange={e=>setVisible(e.target.checked)}/> Show earthquake epicenters</label><p className="muted">Circle radius increases monotonically with magnitude (3 px at M2.5 to 16 px at M8); it is a display scale, not a shaking or damage footprint.</p><label className="thematic-picker">Minimum magnitude<input aria-label="Minimum magnitude" type="range" min="2.5" max="7.5" step="0.5" value={minMag} onChange={e=>setMinMag(Number(e.target.value))}/><span>M{minMag.toFixed(1)}+</span></label><label className="thematic-picker">From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="thematic-picker">To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="thematic-picker">Find event<input type="search" value={query} disabled={!dataset} placeholder="USGS ID, place, magnitude…" onChange={e=>setQuery(e.target.value)}/></label><label className="thematic-picker">Earthquake<select value={selected} disabled={!dataset} onChange={e=>choose(e.target.value)}><option value="">Select an earthquake…</option>{matches.map(f=><option key={String(f.id)} value={String(f.id)}>M{f.properties.magnitude} · {f.properties.event_time?.slice(0,10)} · {f.properties.place_name??'UNKNOWN'}</option>)}</select></label><div className="selection" aria-live="polite">{feature?<><p className="eyebrow">USGS earthquake</p><h3>M{feature.properties.magnitude} · {feature.properties.place_name??'UNKNOWN'}</h3><dl><dt>Origin time</dt><dd>{feature.properties.event_time}</dd><dt>Magnitude</dt><dd>{feature.properties.magnitude} {feature.properties.magnitude_type??'UNKNOWN type'}</dd><dt>Depth</dt><dd>{feature.properties.depth_km} km</dd><dt>Coordinates</dt><dd>{feature.geometry.type==='Point'?`${feature.geometry.coordinates[1].toFixed(4)}, ${feature.geometry.coordinates[0].toFixed(4)}`:'UNKNOWN'}</dd><dt>USGS event ID</dt><dd>{feature.properties.source_id}</dd><dt>Network</dt><dd>{feature.properties.network}</dd><dt>Status</dt><dd>{feature.properties.event_status}</dd></dl></>:<p>Select an event to inspect its preferred ComCat origin. Epicenters do not represent affected or damaged areas.</p>}</div>{dataset&&<details><summary>Earthquake source & limitations</summary><Evidence metadata={dataset.metadata}/></details>}</section>;
}
