import contextTerrain from '../../public/data/asia-terrain-context/1.0.0/manifest.json';
import terrain from '../../public/data/nepal-terrain/1.0.0/manifest.json';
import { parseTerrainManifest } from '../../../../packages/contracts/terrain';
import country from '../../public/data/nepal-admin-country/2.0.1/manifest.json';
import provinces from '../../public/data/nepal-admin-provinces/2.0.1/manifest.json';
import districts from '../../public/data/nepal-admin-districts/2.0.1/manifest.json';
import localLevels from '../../public/data/nepal-admin-local-levels/2.0.1/manifest.json';
import { parseDataset } from '../../../../packages/contracts';
import { Evidence } from '../../components/evidence';
import mountains from '../../public/data/nepal-mountains/1.0.0/manifest.json';
import glaciers from '../../public/data/nepal-glaciers-east/1.0.0/manifest.json';
import rivers from '../../public/data/nepal-rivers-primary/1.0.0/manifest.json';
import glacialLakes from '../../public/data/nepal-transboundary-glacial-lakes/1.0.0/manifest.json';
import infrastructure from '../../public/data/nepal-osm-major-bridges/1.0.0/manifest.json';
import population from '../../public/data/nepal-population/1.0.0/manifest.json';
import { parsePopulationManifest } from '../../../../packages/contracts/population';
import satellite from '../../public/data/nepal-sentinel-observations/1.0.0/manifest.json';
import { parseSatelliteManifest } from '../../../../packages/contracts/satellite';
import climate from '../../public/data/nepal-power-climate/1.0.0/manifest.json';
import { parseClimateManifest } from '../../../../packages/contracts/climate';

export const metadata = { title: 'Data catalog' };
const manifests = [country, provinces, districts, localLevels];
const counts = [1, 7, 77, 775];

export default function CatalogPage() {
  return <div className="page prose"><p className="eyebrow">Data catalog</p><h1>Know what you’re exploring.</h1><p>COD-AB v02 is published as four immutable, checksum-verified presentation datasets. Level 3 contains 753 local-government units and 22 protected or special-area pieces.</p>
    <section className="catalog-entry"><h2>Nepal mountains and peaks</h2><p>747 GeoNames PK and MT records from the pinned 2026-09-07 Nepal dump. Source elevations are retained when present; missing elevations remain UNKNOWN.</p><p><a href="/data/nepal-mountains/1.0.0/manifest.json">Mountain manifest</a> · <a href="/data/nepal-mountains/1.0.0/features.geojson.gz">Compressed GeoJSON</a></p><Evidence metadata={parseDataset({ metadata: mountains, collection: { type: 'FeatureCollection', features: [] } }).metadata} /></section>
    <section className="catalog-entry"><h2>Nepal glaciers</h2><p>4,593 Nepal-intersecting RGI 7.0 glacier outlines are delivered in three geographic browser partitions. Each record retains its stable RGI/GLIMS ID, source area and individual outline date; these are inventory outlines rather than current 2026 margins.</p><p><a href="/data/nepal-glaciers-west/1.0.0/manifest.json">West manifest</a> · <a href="/data/nepal-glaciers-central/1.0.0/manifest.json">Central manifest</a> · <a href="/data/nepal-glaciers-east/1.0.0/manifest.json">East manifest</a></p><Evidence metadata={parseDataset({ metadata: glaciers, collection: { type: 'FeatureCollection', features: [] } }).metadata} /></section>
    <section className="catalog-entry"><h2>Nepal river network</h2><p>18,299 FAO Rivers 2026 / HydroRIVERS reaches preserve stable HYRIV_ID and NEXT_DOWN connectivity. Two browser partitions keep the display within GeoJSON safety budgets without breaking the logical network.</p><p><a href="/data/nepal-rivers-primary/1.0.0/manifest.json">Primary manifest</a> · <a href="/data/nepal-rivers-headwaters/1.0.0/manifest.json">Headwaters manifest</a></p><Evidence metadata={parseDataset({ metadata: rivers, collection: { type: 'FeatureCollection', features: [] } }).metadata} /></section>
    <section className="catalog-entry"><h2>Glacial Lake Observatory</h2><p>4,150 GLO v1.02 unique-lake records cover Nepal and transboundary catchments using published EPSG:4326 centroids and source 2017–2024 mapped extent/change attributes. The layer does not infer a specific glacier, river, or hazard status.</p><p><a href="/data/nepal-transboundary-glacial-lakes/1.0.0/manifest.json">Glacial-lake manifest</a> · <a href="/data/nepal-transboundary-glacial-lakes/1.0.0/features.geojson.gz">Compressed GeoJSON</a></p><Evidence metadata={parseDataset({ metadata: glacialLakes, collection: { type: 'FeatureCollection', features: [] } }).metadata} /></section>
    <section className="catalog-entry"><h2>Nepal infrastructure inventory</h2><p>Build-time OpenStreetMap extracts provide 5,311 major-road ways, 3,004 major bridges, 25,674 schools, 4,654 health facilities, 923 emergency facilities and 4,045 settlements after COD-AB Nepal filtering. Large logical classes are split only for browser delivery.</p><p><a href="/data/nepal-osm-infrastructure/1.0.0/qa.json">Infrastructure QA</a> · <a href="/data/nepal-osm-major-roads-west/1.0.0/manifest.json">Road manifest</a> · <a href="/data/nepal-osm-major-bridges/1.0.0/manifest.json">Bridge manifest</a> · <a href="/data/nepal-osm-schools-west/1.0.0/manifest.json">School manifest</a></p><Evidence metadata={parseDataset({ metadata: infrastructure, collection: { type: 'FeatureCollection', features: [] } }).metadata} /></section>
    <section className="catalog-entry"><h2>Nepal 2025 population estimate</h2><p>WorldPop R2025A v1 constrained population is retained at its native 3 arc-second EPSG:4326 analysis grid. The browser receives a separate 485-tile log-scaled visualization pyramid; those PNG values are display-only and are never treated as population counts.</p><p><a href="/data/nepal-population/1.0.0/manifest.json">Population manifest</a> · <a href="/data/nepal-population/1.0.0/qa.json">Validation report</a> · <a href="/data/nepal-population/1.0.0/source.json">Pinned source record</a></p><Evidence metadata={parsePopulationManifest(population).metadata} /></section>
    <section className="catalog-entry"><h2>Sentinel-2 satellite observations</h2><p>Three fixed Sentinel-2 Collection-1 Level-2A observation windows provide dated true-colour context for western, central and eastern Nepal. Each source TCI/SCL object is pinned by URL, ETag and byte size, while browser previews are checksum-verified local derivatives. These windows are not a seamless national mosaic and are not change-detection outputs.</p><p><a href="/data/nepal-sentinel-observations/1.0.0/manifest.json">Satellite manifest</a> · <a href="/data/nepal-sentinel-observations/1.0.0/sources.json">Scene inventory</a> · <a href="/data/nepal-sentinel-observations/1.0.0/qa.json">Cloud/NoData QA</a></p><Evidence metadata={parseSatelliteManifest(satellite).metadata} /></section>
    <section className="catalog-entry"><h2>Nepal 1991–2020 climate context</h2><p>NASA POWER monthly MERRA-2-derived T2M and PRECTOTCORR values are area-weighted across the unsimplified Nepal COD-AB v02 boundary. The release contains all 360 months from 1991–2020 and 12 derived monthly normals. It is a coarse reanalysis-derived national summary, not a station series, forecast, or local climate surface.</p><p><a href="/data/nepal-power-climate/1.0.0/manifest.json">Climate manifest</a> · <a href="/data/nepal-power-climate/1.0.0/source.json">Pinned API queries</a> · <a href="/data/nepal-power-climate/1.0.0/qa.json">Coverage QA</a></p><Evidence metadata={parseClimateManifest(climate).metadata} /></section>
    <section className="catalog-entry"><h2>Copernicus GLO-90 terrain</h2><p>Native 3 arc-second surface elevations retained offline. Web tiles use EPSG:3857 with EGM2008 heights in metres; hillshade and 3D are derived display products.</p><p><a href="/data/nepal-terrain/1.0.0/manifest.json">Terrain manifest</a> · <a href="/data/nepal-terrain/1.0.0/sources.json">Source inventory</a> · <a href="/data/nepal-terrain/1.0.0/qa.json">Validation report</a> · <a href="/data/nepal-terrain/1.0.0/LICENSE.txt">Licence notices</a></p><Evidence metadata={parseTerrainManifest(terrain).metadata} /></section>
    <section className="catalog-entry"><h2>Asia terrain overview</h2><p>A pinned Mapzen terrain snapshot fills the surrounding map. Context heights are display-only and are not used by the elevation inspector.</p><p><a href="/data/asia-terrain-context/1.0.0/manifest.json">Context manifest</a> · <a href="/data/asia-terrain-context/1.0.0/sources.json">Source inventory</a> · <a href="/data/asia-terrain-context/1.0.0/LICENSE.txt">Source licence notices</a></p><Evidence metadata={parseTerrainManifest(contextTerrain).metadata} /></section>
    <section className="catalog-entry"><h2>Downstream trace results</h2><p>Computed in your browser from both river partitions, with method version, ordered reach IDs, summed source length, termination reason and input hashes available as JSON. No new geographic dataset is published. <a href="/methodology/#downstream-method">Method and limits</a>.</p></section>
    <section className="catalog-entry"><h2>Exposure engine results</h2><p>Two explicitly hypothetical corridors demonstrate native population weighting and deduplicated mapped-asset intersections. <a href="/data/exposure-trace-40669746-250m/1.0.0/manifest.json">250 m result</a> · <a href="/data/exposure-trace-40669746-1000m/1.0.0/manifest.json">1,000 m result</a> · <a href="/methodology/#exposure-method">Method, assumptions and coverage limits</a>. The viewer exposes footprint requests, spatial output and per-input hashes.</p></section>
    <section className="catalog-entry"><h2>Phewa Lake water change</h2><p>Three April Sentinel-2 observations, 2024–2026. Native 20 m masks, exclusions and valid-only comparisons; not Nepal-wide coverage. <a href="/data/phewa-water-change/1.0.0/manifest.json">Manifest and artifact inventory</a> · <a href="/methodology/#water-method">Method and limits</a>.</p></section>
    <section className="catalog-entry"><h2>Observation time index</h2><p>A versioned UTC index of water, satellite, monthly climate and reported event days, with input hashes and separate publication/retrieval dates. <a href="/data/atlas-time-index/1.0.0/index.json">Download index</a> · <a href="/methodology/#time-method">Temporal semantics</a>. Gaps are not interpolated; inventory context keeps its own dates.</p></section>
    <section className="catalog-entry"><h2>Atlas search index</h2><p>A source-derived, immutable index covering 130,794 administrative, geographic, infrastructure and event records in eight bounded gzip shards. It preserves stable dataset/version/feature identity, source-backed aliases, entity type, context and source date. <a href="/data/atlas-search-index/1.0.0/manifest.json">Search manifest</a> · <a href="/methodology/#search-method">Search semantics</a>. The index adds no new geographic facts or names.</p></section>
    <section className="catalog-entry"><h2>Compare mode</h2><p>Compare Mode publishes no new dataset. It resolves two stable Search identities, reloads their exact versioned source records, and applies semantic metric-compatibility rules before showing values. <a href="/methodology/#compare-method">Comparison semantics</a>.</p></section>
    {manifests.map((manifest, index) => {
      const dataset = parseDataset({ metadata: manifest, collection: { type: 'FeatureCollection', features: [] } });
      return <section className="catalog-entry" key={manifest.dataset_id}><h2>{manifest.dataset_name}</h2><p>{counts[index].toLocaleString('en-US')} boundary {counts[index] === 1 ? 'record' : 'records'} · OGC:CRS84 · topology-preserving display geometry</p><p><a href={`/data/${manifest.dataset_id}/2.0.1/manifest.json`}>Download manifest</a> · <a href={manifest.artifact.path}>Download compressed GeoJSON</a></p><Evidence metadata={dataset.metadata} /></section>;
    })}
    <section className="catalog-entry"><h2>Hazard Graph</h2><p>18,811 source-linked nodes and 18,620 evidence-labelled relationships. Drainage connectivity and conditional exposure only; unsupported glacier outlets and blockages remain UNKNOWN. <a href="/data/nepal-hazard-graph/1.0.0/manifest.json">Graph manifest</a>.</p></section>
    <section className="catalog-entry"><h2>Prepared hypothetical scenarios</h2><p>Level 1 network pathway and Level 2 constant-celerity pulse translation, each retaining 180 source reaches with partial downstream coverage. No hazard footprint or physical depth is supplied. <a href="/data/scenario-network-40669746/1.0.0/manifest.json">Network release</a> · <a href="/data/scenario-pulse-40669746/1.0.0/manifest.json">Pulse release</a>.</p></section>
    <section className="catalog-entry"><h2>Simulation UI</h2><p>Feature 29 publishes no new upstream dataset. The browser verifies the two prepared Feature 28 scenario releases, exposes their registered Level 1/2 semantics and recomputes only the same deterministic network approximation for user-selected parameters. Interactive runs remain modelled, local and non-published; footprint, hydraulic depth and exposure stay unavailable when the source scenario contract does not provide them. <a href="/methodology/#simulation-ui-method">Simulation UI semantics</a>.</p></section>
  <section className="catalog-entry"><h2>Evidence corpus</h2><p>Eight pinned project methodology documents provide 154 exact source excerpts, with section/line citations, source hashes, dates and dataset versions. This is a documentation corpus, not an independent observational dataset. <a href="/evidence/">Inspect evidence</a> · <a href="/data/atlas-evidence/1.0.0/manifest.json">Versioned release</a>.</p></section>
  </div>;
}
