'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map, MapLayerMouseEvent } from 'maplibre-gl';
import { isStale, type Dataset } from '../../../../packages/contracts';
import { DataState } from '../../components/data-state';
import { Evidence } from '../../components/evidence';
import { HYDROPOWER_MANIFEST, loadDataset, UnavailableError } from '../../lib/datasets';
import { mountHydropowerDataset } from '../../lib/map-layers';
import type { Resource } from '../../lib/resource';

export function Hydropower({ map }: { map: Map | null }) {
  const [resource,setResource]=useState<Resource<Dataset>>({status:'loading'}); const [attempt,setAttempt]=useState(0); const [visible,setVisible]=useState(true); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const [knownCapacityOnly,setKnownCapacityOnly]=useState(false); const mounted=useRef<ReturnType<typeof mountHydropowerDataset>|null>(null); const dataset='data' in resource?resource.data:null;
  useEffect(()=>{if(!map)return;const controller=new AbortController();let handle:ReturnType<typeof mountHydropowerDataset>|null=null;let click:((event:MapLayerMouseEvent)=>void)|null=null;void(async()=>{try{const data=await loadDataset(HYDROPOWER_MANIFEST,controller.signal);if(controller.signal.aborted)return;handle=mountHydropowerDataset(map,data);mounted.current=handle;handle.setVisible(visible);click=e=>{const id=e.features?.[0]?.id;if(id!==undefined)choose(String(id),data);};map.on('click',handle.interactiveLayers,click);setResource({status:isStale(data.metadata)?'stale':data.collection.features.length?'ready':'empty',data});}catch(error){if(!controller.signal.aborted)setResource({status:error instanceof UnavailableError?'unavailable':'error',message:error instanceof Error?error.message:'Hydropower inventory unavailable'});}})();return()=>{controller.abort();if(handle&&click)map.off('click',handle.interactiveLayers,click);handle?.dispose();mounted.current=null;}; // eslint-disable-next-line react-hooks/exhaustive-deps
  },[map,attempt]); useEffect(()=>{mounted.current?.setVisible(visible);},[visible]);
  const matches=useMemo(()=>{if(!dataset)return[];const needle=query.trim().toLowerCase();return dataset.collection.features.filter(f=>(!knownCapacityOnly||f.properties.capacity_mw!==null)&&(!needle||f.properties.search_terms?.some(t=>t.toLowerCase().includes(needle)))).slice().sort((a,b)=>(b.properties.capacity_mw??-1)-(a.properties.capacity_mw??-1));},[dataset,query,knownCapacityOnly]); const feature=dataset?.collection.features.find(f=>String(f.id)===selected); const capacityKnown=dataset?.collection.features.filter(f=>f.properties.capacity_mw!==null).length??0;
  function choose(id:string,data=dataset){setSelected(id);mounted.current?.setSelected(id||null);const item=data?.collection.features.find(f=>String(f.id)===id);if(item?.geometry.type==='Point'&&map)map.easeTo({center:item.geometry.coordinates as [number,number],zoom:Math.max(map.getZoom(),10),duration:0});}
  return <section className="thematic-controls" aria-label="Hydropower" data-hydropower-state={resource.status}><h2>Hydropower</h2><p>OpenStreetMap plant inventory · {dataset?.collection.features.length??'…'} mapped plants</p>{map?<DataState state={resource} retry={()=>{setResource({status:'loading'});setAttempt(v=>v+1);}}/>:<p className="muted">Hydropower controls require the map.</p>}<label><input type="checkbox" checked={visible} disabled={!dataset} onChange={e=>setVisible(e.target.checked)}/> Show hydropower facilities</label><p className="muted">Facilities cluster at overview zooms. Capacity is known for {capacityKnown} mapped plants. Nearby hazards are geographic context only: proximity does not establish damage, vulnerability or risk.</p><label><input type="checkbox" checked={knownCapacityOnly} disabled={!dataset} onChange={e=>setKnownCapacityOnly(e.target.checked)}/> List only facilities with numeric capacity</label><label className="thematic-picker">Find facility<input type="search" value={query} disabled={!dataset} placeholder="Upper Tamakoshi, OSM way/…, operator…" onChange={e=>setQuery(e.target.value)}/></label><label className="thematic-picker">Hydropower facility<select value={selected} disabled={!dataset} onChange={e=>choose(e.target.value)}><option value="">Select a facility…</option>{matches.map(f=><option key={String(f.id)} value={String(f.id)}>{f.properties.facility_name??f.properties.source_id} · {f.properties.capacity_mw===null?'capacity UNKNOWN':`${f.properties.capacity_mw} MW`}</option>)}</select></label><div className="selection" aria-live="polite">{feature?<><p className="eyebrow">OSM hydropower plant</p><h3>{feature.properties.facility_name??'Name UNKNOWN'}</h3><dl><dt>Capacity</dt><dd>{feature.properties.capacity_mw===null?'UNKNOWN':`${feature.properties.capacity_mw} MW`}</dd><dt>Plant method</dt><dd>{feature.properties.plant_method??'UNKNOWN'}</dd><dt>Operator</dt><dd>{feature.properties.operator_name??'UNKNOWN'}</dd><dt>Status</dt><dd>{feature.properties.facility_status}</dd><dt>OSM ID</dt><dd>{feature.properties.source_id}</dd><dt>OSM snapshot</dt><dd>{feature.properties.osm_source_timestamp}</dd></dl></>:<p>Select a facility to inspect mapped source attributes. Missing capacity or lifecycle status stays UNKNOWN.</p>}</div>{dataset&&<details><summary>Hydropower source & limitations</summary><Evidence metadata={dataset.metadata}/></details>}</section>;
}
