'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map, MapLayerMouseEvent } from 'maplibre-gl';
import { isStale, type Dataset } from '../../../../packages/contracts';
import { DataState } from '../../components/data-state';
import { Evidence } from '../../components/evidence';
import { LANDSLIDES_MANIFEST, loadDataset, UnavailableError } from '../../lib/datasets';
import { mountLandslideDataset } from '../../lib/map-layers';
import type { Resource } from '../../lib/resource';

export function Landslides({ map }: { map: Map | null }) {
  const [resource,setResource]=useState<Resource<Dataset>>({status:'loading'}); const [attempt,setAttempt]=useState(0); const [visible,setVisible]=useState(true); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [verifiedOnly,setVerifiedOnly]=useState(false); const mounted=useRef<ReturnType<typeof mountLandslideDataset>|null>(null); const dataset='data' in resource?resource.data:null;
  useEffect(()=>{if(!map)return;const controller=new AbortController();let handle:ReturnType<typeof mountLandslideDataset>|null=null;let click:((event:MapLayerMouseEvent)=>void)|null=null;void(async()=>{try{const data=await loadDataset(LANDSLIDES_MANIFEST,controller.signal);if(controller.signal.aborted)return;handle=mountLandslideDataset(map,data);mounted.current=handle;handle.setVisible(visible);handle.setFilter(start,end,verifiedOnly);click=e=>{const id=e.features?.[0]?.id;if(id!==undefined)choose(String(id),data);};map.on('click',handle.interactiveLayers,click);setResource({status:isStale(data.metadata)?'stale':data.collection.features.length?'ready':'empty',data});}catch(error){if(!controller.signal.aborted)setResource({status:error instanceof UnavailableError?'unavailable':'error',message:error instanceof Error?error.message:'Landslide archive unavailable'});}})();return()=>{controller.abort();if(handle&&click)map.off('click',handle.interactiveLayers,click);handle?.dispose();mounted.current=null;}; // eslint-disable-next-line react-hooks/exhaustive-deps
  },[map,attempt]); useEffect(()=>{mounted.current?.setVisible(visible);},[visible]); useEffect(()=>{mounted.current?.setFilter(start,end,verifiedOnly);},[start,end,verifiedOnly]);
  const matches=useMemo(()=>{if(!dataset)return[];const needle=query.trim().toLowerCase();return dataset.collection.features.filter(f=>(!start||(f.properties.event_time??'')>=`${start}T00:00:00Z`)&&(!end||(f.properties.event_time??'')<=`${end}T23:59:59Z`)&&(!verifiedOnly||f.properties.verified===true)&&(!needle||f.properties.search_terms?.some(t=>t.toLowerCase().includes(needle)))).slice().sort((a,b)=>(b.properties.event_time??'').localeCompare(a.properties.event_time??'')).slice(0,180);},[dataset,query,start,end,verifiedOnly]); const feature=dataset?.collection.features.find(f=>String(f.id)===selected);
  function choose(id:string,data=dataset){setSelected(id);mounted.current?.setSelected(id||null);const item=data?.collection.features.find(f=>String(f.id)===id);if(item?.geometry.type==='Point'&&map)map.easeTo({center:item.geometry.coordinates as [number,number],zoom:Math.max(map.getZoom(),9),duration:0});}
  return <section className="thematic-controls" aria-label="Landslides" data-landslides-state={resource.status}><h2>Landslides</h2><p>BIPAD historical reported incidents</p>{map?<DataState state={resource} retry={()=>{setResource({status:'loading'});setAttempt(v=>v+1);}}/>:<p className="muted">Landslide controls require the map.</p>}<label><input type="checkbox" checked={visible} disabled={!dataset} onChange={e=>setVisible(e.target.checked)}/> Show reported landslide points</label><p className="muted"><strong>Evidence: REPORTED.</strong> These are incident locations, not landslide polygons, susceptibility scores, probabilities or forecasts.</p><label><input type="checkbox" checked={verifiedOnly} onChange={e=>setVerifiedOnly(e.target.checked)}/> Verified BIPAD records only</label><label className="thematic-picker">From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="thematic-picker">To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="thematic-picker">Find event<input type="search" value={query} disabled={!dataset} placeholder="District, address, incident ID…" onChange={e=>setQuery(e.target.value)}/></label><label className="thematic-picker">Landslide incident<select value={selected} disabled={!dataset} onChange={e=>choose(e.target.value)}><option value="">Select a landslide…</option>{matches.map(f=><option key={String(f.id)} value={String(f.id)}>{f.properties.event_time?.slice(0,10)} · {f.properties.name}</option>)}</select></label><div className="selection" aria-live="polite">{feature?<><p className="eyebrow">reported landslide · not susceptibility</p><h3>{feature.properties.name}</h3><dl><dt>Incident time</dt><dd>{feature.properties.event_time}</dd><dt>Category</dt><dd>{feature.properties.landslide_category}</dd><dt>Evidence</dt><dd>{feature.properties.evidence_status?.toUpperCase()}</dd><dt>Per-event confidence</dt><dd>{feature.properties.confidence??'UNKNOWN — not published by BIPAD'}</dd><dt>Verification</dt><dd>{feature.properties.verified?'verified':'not verified'} / {feature.properties.approved?'approved':'not approved'}</dd><dt>Location text</dt><dd>{feature.properties.street_address??'UNKNOWN'}</dd><dt>Deaths</dt><dd>{feature.properties.reported_deaths??'UNKNOWN'}</dd><dt>Injured</dt><dd>{feature.properties.reported_injured??'UNKNOWN'}</dd><dt>BIPAD incident ID</dt><dd>{feature.properties.source_id}</dd></dl></>:<p>Select a reported landslide to inspect source fields. Failure area, volume and confidence remain UNKNOWN where BIPAD does not provide them.</p>}</div>{dataset&&<details><summary>Landslide source & limitations</summary><Evidence metadata={dataset.metadata}/></details>}</section>;
}
