/** /hazards/ copy. Nepali is project-authored and requires native-speaker review before operational reliance. */
export const HZ = {
  en: {
    eyebrow: 'Hazards · context, not warnings', title: 'Hazard context for Nepal',
    intro: 'Rainfall, snow, dryness, heat and terrain context from verified releases, with links into the scenario simulator. Every panel names its evidence type and source.',
    notice: 'Context and educational scenarios only — not a forecast or warning.', authorities: 'Official forecasts and warnings come only from',
    jump: 'On this page', loading: 'Loading and verifying releases…', failed: 'This release could not be verified, so nothing from it is shown.', retry: 'Try again',
    mapLoading: 'Loading map…', mapFailed: 'The interactive map could not render. All values remain in the tables.',
    mapNoWebgl: 'Interactive mapping is unavailable in this browser (WebGL could not start). All values remain in the tables.',
    overview: 'At a glance', available: 'AVAILABLE', gated: 'GATED', scenario: 'SCENARIO', modelled: 'MODELLED', derived: 'DERIVED',
    cards: {
      flood: ['Floods & GLOF', 'Hypothetical release pulses at 18 verified points; exposure ranges by corridor width.', 'Open flood scenarios'],
      quake: ['Earthquakes', 'BSSA14 shaking scenarios, Gorkha 2015 replay; recent USGS events on Live.', 'Open earthquake scenarios'],
      landslide: ['Landslides', 'District terrain steepness. Susceptibility is UNKNOWN.', 'See terrain context'],
      rain: ['Rainfall & snow', 'Monthly reanalysis anomalies for the latest 12 months.', 'See rainfall and snow'],
      drought: ['Drought & heat', 'SPI-3 dryness and maximum-temperature anomalies.', 'See drought and heat'],
    },
    steepShare: 'of Nepal steeper than 30°', latestMonth: 'Latest month', wetShare: 'area wetter than normal (SPI-3 ≥ 1)', dryShare: 'area drier than normal (SPI-3 ≤ −1)',
    climateTitle: 'Rainfall, snow, drought and heat', climateLead: 'NASA POWER MERRA-2 reanalysis cells (about 55 × 60 km). Choose a month and a view; the table lists every cell.',
    month: 'Month', view: 'View', views: { spi3: 'Drought / wetness (SPI-3)', precip: 'Precipitation, % of 1991–2020 normal', tmax: 'Max temperature anomaly', snow: 'Snow-cover anomaly' },
    viewNotes: {
      spi3: 'SPI-3 compares the latest 3-month total with 1991–2020 for the same months (McKee et al. 1993 classes). Not a drought declaration.',
      precip: 'Monthly mean precipitation as a percentage of the 1991–2020 normal. UNKNOWN where the normal is below 0.1 mm/day.',
      tmax: 'Difference of the month’s highest hourly 2 m temperature from its 1991–2020 normal. Not a heatwave classification.',
      snow: 'Difference in modelled land snow-cover fraction from normal, in percentage points. Model snow is uncertain over high mountains.',
    },
    freshness: 'Snapshot status', staleNote: 'A newer month should now exist; refresh the release before relying on recency.',
    legend: 'Legend', unknown: 'UNKNOWN', selected: 'Selected cell', clickHint: 'Select a cell on the map or in the table.',
    cellTable: 'All cells for the selected month', cell: 'Cell centre', nepalArea: 'Nepal area', precip: 'Precip (mm/day)', pctNormal: '% normal', spi: 'SPI-3', tmax: 'Tmax anomaly (°C)', snowCover: 'Snow cover',
    shareTitle: 'Share of Nepal’s area in each SPI-3 class, by month', shareCaption: 'Area-weighted by each cell’s Nepal area. Bars total 100%.',
    nationalTitle: 'National precipitation: latest 12 months vs 1991–2020 normal', nationalCaption: 'Area-weighted means in mm/day. Bars: month; marks: normal for that calendar month.',
    terrainTitle: 'Landslide terrain context', terrainLead: 'Share of each district steeper than 30° from Copernicus GLO-90 (about 90 m). Steepness is context only: landslide susceptibility, probability and hazard are UNKNOWN.',
    district: 'District', province: 'Province', steep: 'Steeper than 30°', meanSlope: 'Mean slope', elevation: 'Mean elevation', topSteep: 'Ten districts with the largest share steeper than 30°',
    districtTable: 'All 77 districts', reportedNote: 'Reported landslide events are a separate dataset kept out of the public build pending licence review.',
    gatedTitle: 'Gated features', gatedLead: 'Built in a disabled state. Nothing is estimated until every unlock condition is met.',
    gatedCards: [
      ['DHM / NDRRMA-BIPAD feeds', 'Link-only. Needs written redistribution terms or an open licence, a stable documented endpoint, and an adapter that keeps official warning text verbatim.'],
      ['Verified physical flood cases', 'Needs reviewed bathymetry and breach parameters, hydraulic-grade terrain, boundary conditions and validation against an observed event.'],
      ['Earthquake damage', 'Needs a reviewed building taxonomy, fragility functions, replacement costs and validation against a documented event (e.g. Gorkha 2015).'],
    ] as Array<[string, string]>,
    evidenceTitle: 'Ask the evidence', evidenceLead: 'Ranks quoted passages from Atlas documents and release limitations. It does not generate answers or call any external service.',
    question: 'Your question (English words match best)', ask: 'Search evidence', suggestions: 'Try',
    suggested: ['Why is flood depth UNKNOWN?', 'What is SPI-3?', 'Is steepness landslide susceptibility?', 'Earthquake shaking model limitations', 'Why is population outside Nepal UNKNOWN?'],
    answered: 'Passages matching all terms', partial: 'Partial match — some terms not found', insufficient: 'Insufficient evidence in the corpus. This does not mean safe, absent or zero.',
    missing: 'Not found', source: 'Source', provenance: 'Release', methodology: 'Methodology', sources: 'Sources',
    months: 'months', tableView: 'Table view',
  },
  ne: {
    eyebrow: 'जोखिम · सन्दर्भ, चेतावनी होइन', title: 'नेपालका लागि जोखिम सन्दर्भ',
    intro: 'प्रमाणित रिलिजबाट वर्षा, हिउँ, सुक्खापन, गर्मी र भू-बनोटको सन्दर्भ, परिदृश्य सिमुलेटरसम्म लिङ्कसहित। हरेक खण्डले आफ्नो प्रमाण प्रकार र स्रोत देखाउँछ।',
    notice: 'सन्दर्भ र शैक्षिक परिदृश्य मात्र — पूर्वानुमान वा चेतावनी होइन।', authorities: 'आधिकारिक पूर्वानुमान र चेतावनी यिनबाट मात्र आउँछन्:',
    jump: 'यस पृष्ठमा', loading: 'रिलिज लोड र प्रमाणित गर्दै…', failed: 'यो रिलिज प्रमाणित गर्न सकिएन, त्यसैले यसबाट केही देखाइएको छैन।', retry: 'फेरि प्रयास गर्नुहोस्',
    mapLoading: 'नक्सा लोड हुँदैछ…', mapFailed: 'अन्तरक्रियात्मक नक्सा देखाउन सकिएन। सबै मान तालिकामा छन्।',
    mapNoWebgl: 'यस ब्राउजरमा अन्तरक्रियात्मक नक्सा उपलब्ध छैन (WebGL सुरु हुन सकेन)। सबै मान तालिकामा छन्।',
    overview: 'एक नजरमा', available: 'उपलब्ध', gated: 'रोकिएको', scenario: 'परिदृश्य', modelled: 'मोडेल गरिएको', derived: 'व्युत्पन्न',
    cards: {
      flood: ['बाढी र हिमताल विस्फोट', '१८ प्रमाणित बिन्दुमा काल्पनिक बहाव; करिडोर चौडाइ अनुसार जोखिम दायरा।', 'बाढी परिदृश्य खोल्नुहोस्'],
      quake: ['भूकम्प', 'BSSA14 कम्पन परिदृश्य, गोरखा २०१५ दोहोर्याइ; हालका USGS घटना Live मा।', 'भूकम्प परिदृश्य खोल्नुहोस्'],
      landslide: ['पहिरो', 'जिल्लागत भू-बनोटको भिरालोपन। संवेदनशीलता अज्ञात (UNKNOWN) छ।', 'भू-बनोट सन्दर्भ हेर्नुहोस्'],
      rain: ['वर्षा र हिउँ', 'पछिल्ला १२ महिनाको मासिक पुनर्विश्लेषण विचलन।', 'वर्षा र हिउँ हेर्नुहोस्'],
      drought: ['खडेरी र गर्मी', 'SPI-3 सुक्खापन र अधिकतम तापक्रम विचलन।', 'खडेरी र गर्मी हेर्नुहोस्'],
    },
    steepShare: 'नेपालको क्षेत्र ३०° भन्दा भिरालो', latestMonth: 'पछिल्लो महिना', wetShare: 'सामान्यभन्दा भिजेको क्षेत्र (SPI-3 ≥ १)', dryShare: 'सामान्यभन्दा सुक्खा क्षेत्र (SPI-3 ≤ −१)',
    climateTitle: 'वर्षा, हिउँ, खडेरी र गर्मी', climateLead: 'NASA POWER MERRA-2 पुनर्विश्लेषण कोष (करिब ५५ × ६० km)। महिना र दृश्य छान्नुहोस्; तालिकामा सबै कोष छन्।',
    month: 'महिना', view: 'दृश्य', views: { spi3: 'खडेरी / भिजेपन (SPI-3)', precip: 'वर्षा, १९९१–२०२० सामान्यको %', tmax: 'अधिकतम तापक्रम विचलन', snow: 'हिउँ आवरण विचलन' },
    viewNotes: {
      spi3: 'SPI-3 ले पछिल्लो ३ महिनाको जम्मा वर्षालाई सोही महिनाहरूको १९९१–२०२० सँग तुलना गर्छ (McKee et al. 1993 वर्ग)। यो खडेरी घोषणा होइन।',
      precip: 'मासिक औसत वर्षा १९९१–२०२० सामान्यको प्रतिशतमा। सामान्य ०.१ mm/day भन्दा कम भए अज्ञात (UNKNOWN)।',
      tmax: 'महिनाको सबैभन्दा उच्च घण्टाको २ मिटर तापक्रम र १९९१–२०२० सामान्यबीचको फरक। यो तातो लहरको वर्गीकरण होइन।',
      snow: 'मोडेल गरिएको जमिनको हिउँ आवरणमा सामान्यभन्दा फरक, प्रतिशत अंकमा। उच्च हिमालमा मोडेलको हिउँ अनिश्चित छ।',
    },
    freshness: 'स्न्यापसटको अवस्था', staleNote: 'अब नयाँ महिना उपलब्ध हुनुपर्छ; हालको अवस्थामा भर पर्नुअघि रिलिज ताजा गर्नुहोस्।',
    legend: 'सूची', unknown: 'अज्ञात (UNKNOWN)', selected: 'छानिएको कोष', clickHint: 'नक्सा वा तालिकामा कोष छान्नुहोस्।',
    cellTable: 'छानिएको महिनाका सबै कोष', cell: 'कोष केन्द्र', nepalArea: 'नेपालको क्षेत्र', precip: 'वर्षा (mm/day)', pctNormal: 'सामान्यको %', spi: 'SPI-3', tmax: 'अधिकतम तापक्रम विचलन (°C)', snowCover: 'हिउँ आवरण',
    shareTitle: 'महिना अनुसार हरेक SPI-3 वर्गमा नेपालको क्षेत्रको हिस्सा', shareCaption: 'हरेक कोषको नेपाल क्षेत्रले भारित। पट्टीको जम्मा १००%।',
    nationalTitle: 'राष्ट्रिय वर्षा: पछिल्ला १२ महिना र १९९१–२०२० सामान्य', nationalCaption: 'क्षेत्र-भारित औसत, mm/day। पट्टी: महिना; चिन्ह: सोही महिनाको सामान्य।',
    terrainTitle: 'पहिरोका लागि भू-बनोट सन्दर्भ', terrainLead: 'Copernicus GLO-90 (करिब ९० मिटर) बाट हरेक जिल्लाको ३०° भन्दा भिरालो हिस्सा। भिरालोपन सन्दर्भ मात्र हो: पहिरो संवेदनशीलता, सम्भावना र जोखिम अज्ञात (UNKNOWN) छन्।',
    district: 'जिल्ला', province: 'प्रदेश', steep: '३०° भन्दा भिरालो', meanSlope: 'औसत भिरालोपन', elevation: 'औसत उचाइ', topSteep: '३०° भन्दा भिरालो हिस्सा सबैभन्दा बढी भएका दस जिल्ला',
    districtTable: 'सबै ७७ जिल्ला', reportedNote: 'रिपोर्ट गरिएका पहिरो घटना छुट्टै डाटासेट हुन्, इजाजत समीक्षा बाँकी रहेकाले सार्वजनिक संस्करणबाट बाहिर राखिएका छन्।',
    gatedTitle: 'रोकिएका सुविधा', gatedLead: 'निष्क्रिय अवस्थामा बनाइएका। सबै सर्त पूरा नभएसम्म केही अनुमान गरिँदैन।',
    gatedCards: [
      ['DHM / NDRRMA-BIPAD फिड', 'लिङ्क मात्र। लिखित पुनर्वितरण सर्त वा खुला इजाजत, स्थिर दस्तावेजीकृत endpoint, र आधिकारिक चेतावनीको पाठ जस्ताको तस्तै राख्ने adapter चाहिन्छ।'],
      ['प्रमाणित भौतिक बाढी घटना', 'समीक्षा गरिएको तालको गहिराइ र भत्किने मान, हाइड्रोलिक स्तरको भू-बनोट, सीमा अवस्था र अवलोकित घटनासँग प्रमाणीकरण चाहिन्छ।'],
      ['भूकम्प क्षति', 'समीक्षा गरिएको भवन वर्गीकरण, कमजोरी कार्य, प्रतिस्थापन लागत र दस्तावेजीकृत घटना (जस्तै गोरखा २०१५) सँग प्रमाणीकरण चाहिन्छ।'],
    ] as Array<[string, string]>,
    evidenceTitle: 'प्रमाण सोध्नुहोस्', evidenceLead: 'एटलसका कागजात र रिलिजका सीमाबाट उद्धृत अंशहरू क्रमबद्ध गर्छ। यसले उत्तर बनाउँदैन र कुनै बाह्य सेवा प्रयोग गर्दैन।',
    question: 'तपाईंको प्रश्न (अंग्रेजी शब्दहरू राम्रो मिल्छन्)', ask: 'प्रमाण खोज्नुहोस्', suggestions: 'प्रयास गर्नुहोस्',
    suggested: ['Why is flood depth UNKNOWN?', 'What is SPI-3?', 'Is steepness landslide susceptibility?', 'Earthquake shaking model limitations', 'Why is population outside Nepal UNKNOWN?'],
    answered: 'सबै शब्द मिल्ने अंश', partial: 'आंशिक मेल — केही शब्द भेटिएनन्', insufficient: 'संग्रहमा पर्याप्त प्रमाण छैन। यसको अर्थ सुरक्षित, अनुपस्थित वा शून्य होइन।',
    missing: 'भेटिएन', source: 'स्रोत', provenance: 'रिलिज', methodology: 'विधि', sources: 'स्रोतहरू',
    months: 'महिना', tableView: 'तालिका दृश्य',
  },
} as const;
export type HzCopy = (typeof HZ)['en'];
export const hz = (lang: 'en' | 'ne'): HzCopy => HZ[lang] as unknown as HzCopy;
