'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map, MapLayerMouseEvent } from 'maplibre-gl';
import { isStale, type Dataset } from '../../../../packages/contracts';
import { DataState } from '../../components/data-state';
import { Evidence } from '../../components/evidence';
import { FLOODS_MANIFEST, loadDataset, UnavailableError } from '../../lib/datasets';
import { mountFloodDataset } from '../../lib/map-layers';
import type { Resource } from '../../lib/resource';

export function Floods({ map }: { map: Map | null }) {
  const [resource,setResource]=useState<Resource<Dataset>>({status:'loading'}); const [attempt,setAttempt]=useState(0); const [visible,setVisible]=useState(true); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const mounted=useRef<ReturnType<typeof mountFloodDataset>|null>(null); const dataset='data' in resource?resource.data:null;
  useEffect(()=>{if(!map)return;const controller=new AbortController();let handle:ReturnType<typeof mountFloodDataset>|null=null;let click:((event:MapLayerMouseEvent)=>void)|null=null;void(async()=>{try{const data=await loadDataset(FLOODS_MANIFEST,controller.signal);if(controller.signal.aborted)return;handle=mountFloodDataset(map,data);mounted.current=handle;handle.setVisible(visible);handle.setFilter(start,end);click=e=>{const id=e.features?.[0]?.id;if(id!==undefined)choose(String(id),data);};map.on('click',handle.interactiveLayers,click);setResource({status:isStale(data.metadata)?'stale':data.collection.features.length?'ready':'empty',data});}catch(error){if(!controller.signal.aborted)setResource({status:error instanceof UnavailableError?'unavailable':'error',message:error instanceof Error?error.message:'Flood archive unavailable'});}})();return()=>{controller.abort();if(handle&&click)map.off('click',handle.interactiveLayers,click);handle?.dispose();mounted.current=null;}; // eslint-disable-next-line react-hooks/exhaustive-deps
  },[map,attempt]); useEffect(()=>{mounted.current?.setVisible(visible);},[visible]); useEffect(()=>{mounted.current?.setFilter(start,end);},[start,end]);
  const matches=useMemo(()=>{if(!dataset)return[];const needle=query.trim().toLowerCase();return dataset.collection.features.filter(f=>(!start||(f.properties.event_time??'')>=`${start}T00:00:00Z`)&&(!end||(f.properties.event_time??'')<=`${end}T23:59:59Z`)&&(!needle||f.properties.search_terms?.some(t=>t.toLowerCase().includes(needle)))).slice().sort((a,b)=>(b.properties.event_time??'').localeCompare(a.properties.event_time??'')).slice(0,180);},[dataset,query,start,end]); const feature=dataset?.collection.features.find(f=>String(f.id)===selected);
  function choose(id:string,data=dataset){setSelected(id);mounted.current?.setSelected(id||null);const item=data?.collection.features.find(f=>String(f.id)===id);if(item?.geometry.type==='Point'&&map)map.easeTo({center:item.geometry.coordinates as [number,number],zoom:Math.max(map.getZoom(),9),duration:0});}
  return <section className="thematic-controls" aria-label="Floods" data-floods-state={resource.status}><h2>Floods</h2><p>BIPAD historical reported incidents</p>{map?<DataState state={resource} retry={()=>{setResource({status:'loading'});setAttempt(v=>v+1);}}/>:<p className="muted">Flood controls require the map.</p>}<label><input type="checkbox" checked={visible} disabled={!dataset} onChange={e=>setVisible(e.target.checked)}/> Show reported flood points</label><p className="muted"><strong>Evidence: REPORTED.</strong> Blue points are historical incident locations, never inundation footprints, current flood conditions, or modelled hazard.</p><div className="legend-line"><span className="legend-dot"/> Reported flood incident point</div><label className="thematic-picker">From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="thematic-picker">To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="thematic-picker">Find incident<input type="search" value={query} disabled={!dataset} placeholder="District, address, incident ID…" onChange={e=>setQuery(e.target.value)}/></label><label className="thematic-picker">Flood incident<select value={selected} disabled={!dataset} onChange={e=>choose(e.target.value)}><option value="">Select a flood…</option>{matches.map(f=><option key={String(f.id)} value={String(f.id)}>{f.properties.event_time?.slice(0,10)} · {f.properties.name}</option>)}</select></label><div className="selection" aria-live="polite">{feature?<><p className="eyebrow">reported flood · not a footprint</p><h3>{feature.properties.name}</h3><dl><dt>Incident time</dt><dd>{feature.properties.event_time}</dd><dt>Evidence status</dt><dd>{feature.properties.evidence_status?.toUpperCase()}</dd><dt>Geometry meaning</dt><dd>reported incident point</dd><dt>Location text</dt><dd>{feature.properties.street_address??'UNKNOWN'}</dd><dt>Deaths</dt><dd>{feature.properties.reported_deaths??'UNKNOWN'}</dd><dt>Injured</dt><dd>{feature.properties.reported_injured??'UNKNOWN'}</dd><dt>Affected</dt><dd>{feature.properties.reported_affected??'UNKNOWN'}</dd><dt>Estimated loss</dt><dd>{feature.properties.estimated_loss_npr===null?'UNKNOWN':`NPR ${feature.properties.estimated_loss_npr?.toLocaleString('en-US')}`}</dd><dt>BIPAD incident ID</dt><dd>{feature.properties.source_id}</dd></dl></>:<p>Select a reported flood incident. Flood depth, duration and inundation extent are UNKNOWN in this layer.</p>}</div>{dataset&&<details><summary>Flood source & limitations</summary><Evidence metadata={dataset.metadata}/></details>}</section>;
}
