export const metadata = { title: 'Methodology' };

export default function MethodologyPage() {
  return <article className="page prose">
    <p className="eyebrow">Methodology</p><h1>Evidence before interpretation.</h1>
    <p>Every published dataset carries its source, version, dates, license, processing method, coverage, limitations, and uncertainty. Missing measurements remain UNKNOWN.</p>

    <nav className="methodology-toc" aria-label="Methodology sections">
      <strong>On this page</strong>
      <a href="#pipeline-method">Data pipeline & CRS</a><a href="#administrative-method">Boundaries</a><a href="#terrain-method">Terrain</a><a href="#mountains-method">Mountains</a>
      <a href="#rivers-method">Rivers</a><a href="#glaciers-method">Glaciers</a><a href="#glacial-lakes-method">Glacial lakes</a><a href="#population-method">Population</a>
      <a href="#satellite-method">Satellite</a><a href="#climate-method">Climate</a><a href="#events-method">Events</a><a href="#infrastructure-method">Infrastructure</a>
      <a href="#downstream-method">Downstream trace</a><a href="#exposure-method">Exposure</a><a href="#hazard-graph-method">Hazard Graph</a><a href="#scenario-method">Scenario Engine</a>
      <a href="#simulation-ui-method">Simulation UI</a><a href="#search-method">Search</a><a href="#compare-method">Compare</a><a href="#evidence-method">Evidence retrieval</a>
    </nav>

    <h2 id="pipeline-method">Overall data pipeline, CRS and evidence semantics</h2>
    <p>Source acquisition happens offline. Pipelines pin exact source objects or API responses, validate identity and required fields, preserve source licences/dates, transform only what the documented feature requires, then publish immutable browser artifacts with SHA-256 checksums. The public site reads those local artifacts; it does not silently refresh third-party APIs at visitor time. <a href="/data-catalog/">The Data Catalog</a> exposes the release-level lineage and <a href="/sources/">Sources</a> exposes originating providers.</p>
    <p>Vector interchange uses OGC:CRS84 longitude/latitude unless a feature explicitly documents an analysis CRS. Equal-area calculations such as exposure area weighting use EPSG:6933. Native raster CRSs/grids are retained for numerical analysis when required; display reprojection is a separate presentation step. Web Mercator or RGB terrain products are never substituted for the native numerical source merely because they are convenient to render.</p>
    <p>Geometry simplification and tiling are presentation operations unless a feature explicitly defines otherwise. Administrative display geometry is topology-preserving, major-road display geometry is simplified within the documented tolerance, and terrain/satellite display tiles have their own resolutions. Analysis features use the source/native or explicitly prepared analysis geometry named in their methodology rather than inferring precision from pixels on screen.</p>
    <dl className="evidence-terms">
      <dt>Observed</dt><dd>Measurements or records supplied by a documented source.</dd>
      <dt>Historical</dt><dd>Source-reported past events or archival observations; historical does not mean current.</dd>
      <dt>Derived</dt><dd>Deterministic output calculated from source data using a documented method.</dd>
      <dt>Estimated</dt><dd>A quantified estimate whose assumptions/coverage remain explicit; not an observed total.</dd>
      <dt>Modelled</dt><dd>Output produced by a model or hypothetical spatial assumption.</dd>
      <dt>Simulated</dt><dd>A modelled scenario run with explicit parameters; never an official forecast unless a future validated forecasting product explicitly says so.</dd>
      <dt>Unknown</dt><dd>Reliable information is unavailable or the concept is not applicable.</dd>
    </dl>
    <p>Uncertainty is not reduced to one generic score. Each feature preserves the uncertainty/limitations its source or method can support. UNKNOWN, partial coverage, unavailable and incompatible states are intentionally different from zero.</p>

    <h2 id="search-method">Search</h2>
    <p>The global Search index is derived offline from the exact immutable atlas releases and split into eight gzip shards, each capped at 2 MiB compressed and 16 MiB decoded. Every indexed record keeps its source dataset/version, stable feature/source ID, entity type, representative position, source date and disambiguating context. The browser verifies each shard checksum before use and processes shards sequentially on explicit search submission.</p>
    <p>Unicode NFKD normalization supports diacritic-insensitive matching without inventing different-script transliterations. Ranking is canonical exact, alias/stable-ID exact, canonical prefix, alias prefix, canonical substring, alias substring, then explicit type terms with deterministic tie-breaking. Duplicate canonical names remain separate results. Current HydroRIVERS reaches and GLO records have no verified common-name linkage in these releases, so unsupported river/lake names are not manufactured.</p>

    <h2 id="compare-method">Compare Mode</h2>
    <p>Compare Mode uses Search only to resolve stable identities, then reloads the two exact versioned source datasets. The current contract supports district-to-district, mountain-to-mountain, river-reach-to-river-reach, glacier-to-glacier, glacial-lake-to-glacial-lake, BIPAD-event-to-BIPAD-event and USGS-earthquake-to-USGS-earthquake comparisons. Arbitrary Location Explorer coordinates are excluded because no versioned numerical location snapshot is published yet.</p>
    <p>Compatibility depends on entity family, metric definition and unit; equal units alone do not make two measurements comparable. Missing values remain UNKNOWN, source zero remains zero, and incompatible metrics are blocked. BIPAD nominal estimated loss is excluded because values are not normalized across years. The UI never ranks entities and always shows source, dataset version, dates, temporal coverage, spatial resolution and evidence type for both sides.</p>

    <h2 id="simulation-ui-method">Simulation UI</h2>
    <p>The Feature 29 workbench is a user interface over Feature 28’s registered network approximations, not a new physical hazard model. Before execution it verifies both immutable scenario examples and requires the same source HYRIV reach, input dataset versions/hashes and ordered pathway. Level 1 uses <code>network-path@1.0.0</code> with no physical parameters. Level 2 uses <code>constant-celerity-pulse@1.0.0</code> with explicit celerity (0.1–10 m/s), hypothetical release volume (0–10,000,000 m³) and duration (60–86,400 s). Invalid or nonfinite values are blocked before calculation, and Level 3+ remains unavailable because no physical adapter is registered.</p>
    <p>Level 2 applies only the validated translation equations already documented by the Scenario Engine: source cumulative reach length divided by user-assumed signal celerity gives relative entry/exit delays; duration extends the rectangular pulse; volume divided by duration gives signal discharge. Celerity is not measured water velocity and relative delays are not predicted arrival times. Default values independently reproduce the published Feature 28 reference calculation; custom values have no separate real-event or published-reference validation.</p>
    <p>Every result is labelled <strong>MODELLED SCENARIO — NOT AN OFFICIAL FORECAST</strong>, retains model/version, exact input source/version/hash metadata, assumptions, partial network coverage, validation status and limitations, and keeps source-derived geometry separate from modelled quantities. Current models return no inundation footprint, depth, hydraulic velocity or confidence interval, so the UI reports those as UNKNOWN and does not run the Exposure Engine. Side-by-side run comparison is allowed only for the same level, model/version and verified source pathway. Flat and perspective map views share exactly one simulation output; camera perspective does not change the model.</p>

    <h2 id="time-method">Time Machine</h2>
    <p>One UTC observation date synchronizes water imagery/comparisons, satellite context, monthly climate and reported event days. Acquisition, source publication and retrieval remain separate. Missing dates stay unavailable; no nearest date is substituted. Monthly data remain whole monthly aggregates. Events use occurrence dates, not report dates. Before/after water imagery shares a grid and chronological dates, while its quality gate still governs measured change. Different satellite footprints cannot form a change comparison. Other inventories and scenario layers retain their own dates and are not reconstructed historically.</p>

    <h2 id="water-method">Water Change</h2>
    <p>Three April Sentinel-2 observations around Phewa Lake share a native 20 m UTM grid. Calibrated green/NIR reflectance, NDWI above 0.05 and SCL water must agree. Land requires NDWI below −0.05 and valid non-water SCL. Clouds, shadows, snow, a 20 m exclusion buffer, uncertain pixels and water patches below 0.0036 km² remain UNKNOWN. Only jointly valid pixels contribute to gain, loss and persistence. Both full-window and mapped-water-union coverage must reach 80%; failing comparisons have UNKNOWN metrics. Display masks are reprojected separately from native area counts.</p>
    <p>These dates do not establish seasonal behaviour, trends, flood extent or causes. Mapped area is partial coverage, not total lake area. Cross-sensor, atmospheric and shoreline uncertainty remain; no independent accuracy estimate is available. <a href="/data/phewa-water-change/1.0.0/qa.json">Coverage QA</a> · <a href="/data/phewa-water-change/1.0.0/sources.json">Source windows and calibration</a>.</p>

    <h2 id="population-method">Population preparation</h2>
    <p>The Atlas pins the WorldPop Nepal 2025 R2025A v1 constrained Float32 GeoTIFF by SHA-256 and validates its EPSG:4326 CRS, 9,773 × 4,921 dimensions, 3 arc-second cell spacing, <code>-99999</code> NoData value, finite non-negative valid cells, and source raster bounds. Valid zero population cells remain distinct from NoData.</p>
    <p>The native source raster remains the numerical analysis input. A separate EPSG:3857 zoom 5–10 PNG pyramid is generated only for visualization using bilinear reprojection and a log-scaled intensity transform. Display pixels therefore cannot be sampled or summed as population counts. The national source-cell sum is retained as an integrity check, not presented as a census total or an administrative validation target.</p>
    <p>Future exposure calculations must use the pinned native people-per-grid-cell raster and explicitly define raster/vector alignment, NoData handling and partial-cell weighting. The current layer performs no hazard exposure estimate.</p>

    <h2 id="satellite-method">Satellite observation preparation</h2>
    <p>The Atlas uses three fixed Sentinel-2 Collection-1 Level-2A observations selected from 1 April through 15 June 2026 as separate western, central and eastern context windows. Candidate scenes must have source cloud cover at or below 5% and zero Scene Classification Layer NoData. The selected 10 m true-colour COG and 20 m SCL objects are pinned by exact URL, ETag and byte size before they are read; a changed upstream object fails the build instead of silently replacing a release input.</p>
    <p>The SCL is independently counted for cloud classes 8, 9 and 10, NoData class 0 and snow/ice class 11. A 768 × 768 RGB preview is then produced from each full-resolution TCI by bilinear resampling and checksum-verified in the browser before display. The preview does not retain 10 m analytical resolution. Clouds, shadows, snow and visual differences between observation dates remain image content only: this feature performs no water classification, land classification or change detection.</p>
    <p>The three scenes have different acquisition timestamps and disjoint/overlapping footprints, so they are deliberately presented as observation windows rather than a seamless or single-date Nepal mosaic. Areas outside those footprints are unavailable, not filled from another source.</p>

    <h2 id="climate-method">Climate preparation</h2>
    <p>The Atlas acquires NASA POWER monthly <code>T2M</code> and <code>PRECTOTCORR</code> for 1991–2020 from the source-native MERRA-2 grid. The API reports 0.5° latitude × 0.625° longitude spacing, UTC monthly periods, temperature in degrees Celsius and corrected precipitation as a mean daily rate in mm/day. POWER annual fields are deliberately excluded; no daily or station-level precision is reconstructed from monthly data.</p>
    <p>For each of the 360 months, every POWER grid box intersecting Nepal is overlaid with the pinned, unsimplified COD-AB v02 national boundary. Intersection pieces are transformed to equal-area EPSG:6933, and valid grid values are weighted by the Nepal area inside each cell. The release uses 66 contributing grid cells and requires complete valid-area coverage; every published month has 100% coverage. This produces a Nepal-wide national summary, not a local interpolation or a new climate raster.</p>
    <p>The 12 displayed 1991–2020 monthly normals are arithmetic means of the 30 area-weighted values for each calendar month. The accompanying minimum and maximum are the range of those 30 monthly reanalysis values and show historical reanalysis variability only; they are not confidence intervals or measurement uncertainty. MERRA-2 assimilation, model physics, topographic representation and POWER processing limitations remain applicable. The baseline is historical context, not a forecast or current-condition estimate.</p>

    <h2 id="exposure-method">Exposure engine</h2>
    <p>Exposure means a spatial intersection with an explicit footprint. It does not establish vulnerability, risk, confirmed damage or losses. The prepared corridors are hypothetical areas of interest around one retained downstream trace, with assumed widths of 250 m and 1,000 m each side. They are not flood simulations.</p>
    <p>The offline engine accepts versioned, valid Polygon or MultiPolygon footprints in OGC:CRS84 within the Nepal region. Event points and bare river lines are not exposure areas. It overlays the pinned native WorldPop 2025 GeoTIFF, never the population display tiles. For each valid source cell, its population is multiplied by the intersected fraction of cell area in equal-area EPSG:6933, then summed. This assumes uniform population within a cell. Native resolution is preserved and results are rounded to people for display.</p>
    <p>NoData and out-of-grid areas remain UNKNOWN. A known-cell subtotal is shown separately, and any unknown area makes the whole-footprint population estimate UNKNOWN. No uncertainty interval is invented. OSM geometry intersection counts mapped points, lines and polygons, including boundary contact; polygons count as whole assets. Shared OSM IDs are deduplicated, while road and bridge representations are tested separately. Buildings and dams have no inventory in this calculation.</p>
    <p>District area pieces are made disjoint in P-code order, with unassigned coverage retained. Each matched asset is assigned to the greatest intersected district area or length, with lowest P-code breaking ties. Category counts can overlap and must not be added as a unique total. Source geometry simplification, representative facility centres, mapping completeness and differing source dates limit interpretation.</p>
    <p>Calculations run offline to avoid national raster processing in a visitor’s browser. Downloaded result JSON, footprint requests and spatial layers record source versions/hashes, calculation timestamp, method version, CRS, assumptions and limitations. A new footprint is computed through the offline pipeline and published as a new immutable result before it is registered in the viewer.</p>

    <h2 id="downstream-method">Downstream trace</h2>
    <p>The Atlas combines both verified Nepal river partitions and follows HYRIV_ID / NEXT_DOWN pointers from a selected whole reach. Duplicate IDs, inconsistent internal links, invalid lengths and cycles prevent tracing. Each retained reach is counted once, and LENGTH_KM values are summed in kilometres. The first downstream ID outside this release ends the trace with a coverage-boundary notice; an absent source connection is labelled a source outlet.</p>
    <p>Results are ATLAS DERIVED network analyses. Gold lines and playback show reach order, not a flood footprint, flow velocity or travel time. The selected reach is included in full, irrespective of where it was clicked. Source geometry is unchanged, with no inferred connections across gaps. The downloaded JSON records method version, ordered reach IDs, termination, source versions, hashes and limitations.</p>
    <p>Lake/glacier outlet links and settlement, infrastructure and population intersections remain UNKNOWN. A shared basin or nearby river is insufficient to establish an outlet connection. No terrain-flow or hydraulic model is used. See the <a href="https://data.hydrosheds.org/file/technical-documentation/HydroRIVERS_TechDoc_v10.pdf">HydroRIVERS attribute definitions</a>.</p>

    <h2 id="glacial-lakes-method">Glacial-lake preparation</h2>
    <p>The Atlas pins the GLO v1.02 Sentinel-2 unique-lake centroid and polygon-attribute GeoPackages by SHA-256 and joins them by stable GLO_ID. The EPSG:4326 source centroids are used directly for browser geometry, while source equal-area polygon area/perimeter attributes are retained without reprojecting those polygons.</p>
    <p>AREA_DISSOLVED is the source dissolved maximum mapped extent across 2017–2024, not a current lake-area measurement. Expansion rate, uncertainty and significance are source time-series/statistical fields and are never converted into a hazard class. Specific glacier and river links remain UNKNOWN because this source layer does not identify them.</p>

    <h2 id="glaciers-method">Glacier inventory preparation</h2>
    <p>The Atlas pins RGI 7.0 South Asia West and South Asia East WFS subsets by SHA-256, selects complete glacier features intersecting the validated Nepal country polygon, and retains stable RGI/GLIMS IDs, source area, source outline date and RGI elevation attributes.</p>
    <p>Some GLIMS WFS display geometries are invalid after its coordinate transformation. Only the browser geometry is repaired with make_valid and topology-preserving simplification; source RGI area remains the measurement. QA records every repair, and the UI labels every outline as a dated inventory record rather than a current margin.</p>

    <h2 id="rivers-method">River network preparation</h2>
    <p>The Atlas selects every FAO Rivers 2026 reach whose complete source geometry intersects Nepal. It does not clip or simplify the network. HYRIV_ID and NEXT_DOWN are retained so later downstream analysis can follow source topology, including links crossing the two browser-delivery partitions.</p>
    <p>The partitions exist only to keep decoded GeoJSON under 8 MiB. Average discharge and flow-regime attributes are long-term/source descriptors, not live hydrological observations.</p>

    <h2 id="mountains-method">Mountain catalogue preparation</h2>
    <p>The atlas pins the GeoNames Nepal country dump by SHA-256, selects only terrain feature codes PK and MT, retains stable GeoNames IDs, source coordinates, explicit source elevations, names and bounded aliases, and rejects duplicate IDs or implausible coordinates/elevations. The GeoNames DEM fallback is deliberately not substituted for a missing summit elevation.</p>

    <h2 id="infrastructure-method">Infrastructure preparation</h2>
    <p>The Atlas pins one build-time OpenStreetMap snapshot for bridge/facility/settlement positions and five smaller major-road geometry slices by SHA-256. The road slices are merged by stable OSM way ID; repeated slice occurrences are removed without geographic/name heuristics. Every retained point is inside the unsimplified Nepal COD-AB v02 country polygon, and road ways are intersected with that polygon before browser simplification.</p>
    <p>Major roads retain source way geometry but use a topology-preserving 0.0002° display simplification. School, health, emergency and bridge ways/relations are represented by source-provided Overpass centres for browser exploration; those points do not replace source OSM geometry for future precise analysis. Buildings are deliberately omitted because uneven national OSM completeness would make exposure counts misleading. Inventory presence is not an exposure, vulnerability, damage or risk result.</p>

    <h2 id="administrative-method">Administrative boundary preparation</h2>
    <p>The atlas pins the Nepal COD-AB v02 source archive by SHA-256. The offline pipeline checks the expected 1 country, 7 provinces, 77 districts, and 775 level-3 pieces; unique P-codes; closed and valid Polygon or MultiPolygon geometry; parent containment; neighboring units; and complete Nepal coverage without unexplained gaps or overlaps.</p>
    <p>Level 3 includes 753 local-government units and 22 protected or special-area pieces. The atlas retains both categories because together they cover Nepal. Ward boundaries are unavailable in this release.</p>

    <h2 id="display-geometry-method">Display and analysis geometry</h2>
    <p>The source uses OGC:CRS84 longitude and latitude. Administrative web geometry is simplified as a shared coverage so neighboring edges remain aligned, then compressed for delivery. It supports identification and display only. Pinned unsimplified/raw sources remain outside the browser for future analysis where licensing permits.</p>

    <h2 id="events-method">Reported events and hazard records</h2>
    <p>BIPAD disaster events, USGS earthquakes, reported floods and reported landslides remain source-reported records. Event points are locations supplied by their source; they are not automatically affected-area polygons. Reported casualty/loss fields remain source values, missing values stay UNKNOWN, and event-page narrative is limited to supported source fields. Proximity to a reported event does not establish exposure, damage, cause or future hazard.</p>

    <h2 id="terrain-method">Terrain preparation</h2>
    <p>Copernicus GLO-90 native Float32 rasters are retained at their original 3 arc-second sample spacing and aligned in an offline analysis mosaic without resampling. The source is a surface model, including buildings and vegetation, with EGM2008 heights in metres.</p>
    <p>Web display uses bilinear reprojection to aligned Web Mercator grids and Terrain RGB tiles at zooms 5–9. Each tile is checked against its recorded SHA-256 before rendering. Finest display spacing is roughly 270 m near Nepal; encoding in 0.1 m increments is not an accuracy claim. Elevation inspection always samples that finest display grid, independently of map zoom and visual exaggeration. Hillshade is a derived lighting effect, not an observation or slope analysis.</p>
    <p>A full rectangular tile domain surrounding Nepal prevents artificial zero-height seams at national borders. Regional plausibility probes are checked near Everest, Kathmandu and Biratnagar; they do not substitute for survey validation. No hydrological conditioning or bare-earth correction is performed.</p>

    <h2>Regional overview</h2>
    <p>A pinned Mapzen terrain pyramid fills the Asia overview. Its source heights are not normalized to the Copernicus vertical datum and are not used for measurement. Negative heights are displayed as sea surface. In the context buffer outside Nepal, display heights transition over one degree between the detailed tile domain and the coarse backdrop; interpolation operates on decoded heights, never on RGB colour channels. Copernicus elevation inspection reads the original verified tiles.</p>

    <h2>Research boundary</h2>
    <p>No operational forecast, hazard classification, confirmed-damage estimate or risk score is included in this release. The exposure engine reports explicitly hypothetical spatial intersections, while source-reported areas, satellite imagery and change statistics remain descriptive evidence rather than predictions or impact claims.</p>
    <h2 id="hazard-graph-method">Hazard Graph</h2><p>Directed edges carry source records, methods, evidence class and assumptions. River NEXT_DOWN links are derived drainage topology. Corridor exposure links are modelled and conditional on hypothetical footprints. Dashed inferred/modelled links are never presented as observed causes. Missing links and unsupported confidence remain UNKNOWN. Diagram positions are schematic; traversal is bounded and cycle-safe.</p>
    <h2 id="scenario-method">Scenario Engine</h2><p>Level 1 traces source NEXT_DOWN pointers. Level 2 translates a hypothetical rectangular release at one explicitly assumed celerity: delay equals source distance divided by celerity and discharge equals volume divided by duration. No attenuation, terrain hydraulics, depth, flood footprint or water velocity is calculated. Celerity is not water velocity. These are educational network approximations with synthetic analytical validation only, not forecasts or emergency predictions. Coverage exits and unsupported quantities remain explicit.</p><p>Definitions, assumptions, model versions, units, source hashes and processing versions accompany every result. Invalid inputs fail offline before publication; the browser only inspects immutable, verified runs. <a href="https://www.hec.usace.army.mil/confluence/hmsdocs/hmstrm/channel-flow/lag-model">USACE lag-model concept</a> provides context for translation without attenuation; the Atlas does not execute or claim calibration from HEC-HMS.</p>
  <h2 id="evidence-method">Evidence retrieval</h2><p>The <a href="/evidence/">evidence browser</a> retrieves exact excerpts from eight versioned Atlas methodology documents. It preserves document hashes, sections, dates and linked dataset manifests. These are project descriptions, not independent observations or a complete report archive. Keyword matches do not establish factual support; missing evidence and UNKNOWN freshness remain explicit. <a href="/data/atlas-evidence/1.0.0/manifest.json">Corpus release</a>.</p>
  <h2>AI Analyst</h2><p>The <a href="/analyst/">local analyst</a> answers supported questions using exact project-document excerpts, verified downstream topology and registered hypothetical scenarios. Citations retain source versions, dates and limitations. Calculations and modelled results remain distinct from observations; unsupported measurements and interpretations stay UNKNOWN. It introduces no new upstream source or runtime language-model service.</p>
  </article>;
}
