'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map, MapLayerMouseEvent } from 'maplibre-gl';
import { isStale, type Dataset } from '../../../../packages/contracts';
import { DataState } from '../../components/data-state';
import { Evidence } from '../../components/evidence';
import { loadDataset, RAINFALL_MANIFEST, UnavailableError } from '../../lib/datasets';
import { mountRainfallDataset } from '../../lib/map-layers';
import type { Resource } from '../../lib/resource';

export function Rainfall({ map }: { map: Map | null }) {
  const [resource,setResource]=useState<Resource<Dataset>>({status:'loading'}); const [attempt,setAttempt]=useState(0); const [visible,setVisible]=useState(true); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const mounted=useRef<ReturnType<typeof mountRainfallDataset>|null>(null); const dataset='data' in resource?resource.data:null;
  useEffect(()=>{if(!map)return; const controller=new AbortController(); let handle:ReturnType<typeof mountRainfallDataset>|null=null; let click:((event:MapLayerMouseEvent)=>void)|null=null; void(async()=>{try{const data=await loadDataset(RAINFALL_MANIFEST,controller.signal); if(controller.signal.aborted)return; handle=mountRainfallDataset(map,data); mounted.current=handle; handle.setVisible(visible); click=e=>{const id=e.features?.[0]?.id;if(id!==undefined)choose(String(id),data);}; map.on('click',handle.interactiveLayers,click); setResource({status:isStale(data.metadata)?'stale':data.collection.features.length?'ready':'empty',data});}catch(error){if(!controller.signal.aborted)setResource({status:error instanceof UnavailableError?'unavailable':'error',message:error instanceof Error?error.message:'Rainfall unavailable'});}})(); return()=>{controller.abort(); if(handle&&click)map.off('click',handle.interactiveLayers,click);handle?.dispose();mounted.current=null;}; // eslint-disable-next-line react-hooks/exhaustive-deps
  },[map,attempt]); useEffect(()=>{mounted.current?.setVisible(visible);},[visible]);
  const matches=useMemo(()=>{if(!dataset)return[];const needle=query.trim().toLowerCase();const items=needle?dataset.collection.features.filter(f=>f.properties.search_terms?.some(t=>t.toLowerCase().includes(needle))):dataset.collection.features;return items.slice().sort((a,b)=>(b.properties.observation_time??'').localeCompare(a.properties.observation_time??'')).slice(0,150);},[dataset,query]); const feature=dataset?.collection.features.find(f=>String(f.id)===selected);
  function choose(id:string,data=dataset){setSelected(id);mounted.current?.setSelected(id||null);const item=data?.collection.features.find(f=>String(f.id)===id);if(item?.geometry.type==='Point'&&map)map.easeTo({center:item.geometry.coordinates as [number,number],zoom:Math.max(map.getZoom(),9),duration:0});}
  return <section className="thematic-controls" aria-label="Rainfall" data-rainfall-state={resource.status}><h2>Rainfall</h2><p>BIPAD / DHM gauge snapshot</p>{map?<DataState state={resource} retry={()=>{setResource({status:'loading'});setAttempt(v=>v+1);}}/>:<p className="muted">Rainfall controls require the map.</p>}<label><input type="checkbox" checked={visible} disabled={!dataset} onChange={e=>setVisible(e.target.checked)}/> Show rainfall stations</label><p className="muted">Missing accumulation is UNKNOWN, not zero. This cached snapshot is not a live warning service.</p><label className="thematic-picker">Find station<input type="search" value={query} disabled={!dataset} placeholder="Koshi, Tumlingtar, station ID…" onChange={e=>setQuery(e.target.value)}/></label><label className="thematic-picker">Rainfall station<select value={selected} disabled={!dataset} onChange={e=>choose(e.target.value)}><option value="">Select a station…</option>{matches.map(f=><option key={String(f.id)} value={String(f.id)}>{f.properties.station_name} · {f.properties.rainfall_24h_mm===null?'UNKNOWN':`${f.properties.rainfall_24h_mm} mm / 24h`}</option>)}</select></label><div className="selection" aria-live="polite">{feature?<><p className="eyebrow">rainfall station</p><h3>{feature.properties.station_name}</h3><dl><dt>Observed</dt><dd>{feature.properties.observation_time}</dd><dt>1 h</dt><dd>{feature.properties.rainfall_1h_mm===null?'UNKNOWN':`${feature.properties.rainfall_1h_mm} mm`}</dd><dt>3 h</dt><dd>{feature.properties.rainfall_3h_mm===null?'UNKNOWN':`${feature.properties.rainfall_3h_mm} mm`}</dd><dt>6 h</dt><dd>{feature.properties.rainfall_6h_mm===null?'UNKNOWN':`${feature.properties.rainfall_6h_mm} mm`}</dd><dt>12 h</dt><dd>{feature.properties.rainfall_12h_mm===null?'UNKNOWN':`${feature.properties.rainfall_12h_mm} mm`}</dd><dt>24 h</dt><dd>{feature.properties.rainfall_24h_mm===null?'UNKNOWN':`${feature.properties.rainfall_24h_mm} mm`}</dd><dt>Quality flag</dt><dd>{feature.properties.rainfall_quality_warning?'SOURCE RANGE WARNING':'no atlas range warning'}</dd><dt>Status</dt><dd>{feature.properties.station_status}</dd><dt>Basin</dt><dd>{feature.properties.basin??'UNKNOWN'}</dd><dt>Provider</dt><dd>{feature.properties.provider}</dd></dl></>:<p>Select a station to inspect source accumulation intervals.</p>}</div>{dataset&&<details><summary>Rainfall source & limitations</summary><Evidence metadata={dataset.metadata}/></details>}</section>;
}
